### ISSUE TITLE
error: no files found in upload directory, when directory is full of files

### ISSUE THREAD

**Issue by ysig** [WoLpH/sphinx-pypi-upload#3]
In a circleci project I am using your library in the following way:
After I have built the documentation manually I have saved all html files in a certain directory.
Afterwards i copy all these files to a folder called upload_dir where the files are all under html.
Wanting to utilise on the upload_sphinx part of your package I get the following error which seems really strange:

> running upload_sphinx
> error: no files found in upload directory '/home/circleci/project/upload_dir/html'

whereas I can see that this file exists.
To understand the error based on its commands, you can see the [script that is being executed](https://github.com/ysig/GraKeL/blob/develop/ci_scripts/circleci/pypi_deploy.sh) and its [behavior](https://circleci.com/gh/ysig/GraKeL/682) inside the travis environment.

Thanks in advance for your time!

**Comment by wolph** [comment]
I apologize for not responding sooner... I've completely missed this issue.
Your problem actually stems from the original (dead) sphinx-pypi-upload project and I encountered the same bug which is why I created this fork. If you install `Sphinx-PyPI-upload-2` the problem is solved.

Regardless, I think the point is moot because uploading documentation to pypi has become deprecated in favour of ReadTheDocs.
